### ISSUE TITLE
bug with get-passhashes

### ISSUE THREAD

**Issue by zhutougg** [Mr-B0b/SpaceRunner#1]
spacerunner.exe -i Get-PassHashes.ps1 -o Get-PassHashes.exe -f Get-PassHashes
when I execute Get-PassHashes.exe
 [x] 值不能为 null。
参数名: destination
 [x]

未经处理的异常:  System.Management.Automation.Runspaces.PSSnapInException: Cannot load Windows PowerShell snap-in Microsoft.PowerShell.Diagnostics because of the following error: 未能加载文件或程序集
“Microsoft.PowerShell.Commands”或它的某一个依赖项。系统找不到指定的文件。
   在 System.Management.Automation.Runspaces.RunspaceConfigForSingleShell.LoadMshSnapinAssembly(PSSnapInInfo mshsnapinInfo)
   在 System.Management.Automation.Runspaces.RunspaceConfigForSingleShell.LoadPSSnapIn(PSSnapInInfo mshsnapinInfo)
   在 System.Management.Automation.Runspaces.RunspaceConfigForSingleShell.LoadPSSnapIns(Collection`1 mshsnapinInfos, PSConsoleLoadException& warning)
   在 System.Management.Automation.Runspaces.RunspaceConfigForSingleShell.CreateDefaultConfiguration()
   在 System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(PSHost host)
   在 Application.Program.Main()

**Comment by Mr-B0b** [comment]
Hi @zhutougg,
Are you referring to the [Get-PassHashes.ps1](https://github.com/samratashok/nishang/blob/master/Gather/Get-PassHashes.ps1) PowerShell script from [Nishang](https://github.com/samratashok/nishang) framework ?

If so, I also compiled the C# binary:
![image](https://user-images.githubusercontent.com/6248411/88518434-c6a4a100-cff0-11ea-9ceb-a36d23f1f77b.png)

And ran the compiled binary from an elevated shell without any issue:
![image](https://user-images.githubusercontent.com/6248411/88518474-d7551700-cff0-11ea-8e6d-d23e90baa94d.png)

Can you check that the compilation went without error ?

Regards,
